In [1]:
import pyodbc
import pandas as pd
import numpy as np
import os

In [2]:
conn_lims = pyodbc.connect("Driver={SQL Server};"
                        "Server=192.168.5.18\CROPNUT;"
                        "Database=cropnuts;"
                        "uid=thomasTsuma;pwd=GR^KX$uRe9#JwLc6")

In [3]:
commercial = pd.read_csv("Commercial.csv")

In [4]:
farmlab = pd.read_csv("FarmLab.csv")

In [5]:
agviza = pd.read_csv("AgViza.csv")

In [6]:
df = pd.concat([commercial, farmlab, agviza])

In [7]:
df.to_csv("Nutrient_Req.csv")

In [22]:
df

,Unnamed: 0,client_id,client_name,farm_name,client_type,crop_code,crop_name,chemical_name,chemical_code,use_nutrient_req,yieldTargetsMatchesMasterCrop,UsesYieldVsSoilTestRange
0,0,293,Cropnuts Internal,Quality Control,Commercial,23,ma,P,19,False,False,True
1,1,5528,Malawi Fertiliser Company,Malawi Fertilizer Company,Commercial,69,Tobacco,P,19,False,False,True
2,2,5528,Malawi Fertiliser Company,Malawi Fertilizer Company,Commercial,69,Tobacco,K,1,False,False,True
3,3,6598,Yara Kenya,Yara-Migori,Commercial,702,Potatoes (Irish),P,19,False,False,True
4,4,577,Yara East Africa Ltd,Kiambu Zone,Commercial,1112,Maize (Silage),P,19,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
23779,23779,39057,Human Practice Foundation,NaN,AgViza,1651,Sorghum (Hybrid),K,1,False,False,True
23780,23780,39057,Human Practice Foundation,NaN,AgViza,1650,Sorghum (OPV),P,19,False,False,True
23781,23781,39057,Human Practice Foundation,NaN,AgViza,1650,Sorghum (OPV),K,1,False,False,True
23782,23782,39057,Human Practice Foundation,NaN,AgViza,1646,Tomatoes (Hybrid),P,19,False,False,True
23783,23783,39057,Human Practice Foundation,NaN,AgViza,1646,Tomatoes (Hybrid),K,1,False,False,True

In [16]:
df.columns

Index(['Unnamed: 0', 'client_id', 'client_name', 'farm_name', 'client_type',
       'crop_code', 'crop_name', 'chemical_name', 'chemical_code',
       'use_nutrient_req', 'yieldTargetsMatchesMasterCrop',
       'UsesYieldVsSoilTestRange'],
      dtype='object')

In [9]:
summary = pd.DataFrame()

In [19]:
df['UsesYieldVsSoilTestRange'].value_counts()

True    94876
Name: UsesYieldVsSoilTestRange, dtype: int64

In [25]:
arr = []

In [26]:
for client_type,crop_code,crop_name,chemical_code in zip(df['client_type'], df['crop_code'], df['crop_name'],df['chemical_code']):
    _ = df.loc[(df['client_type'] == client_type) & (df['crop_code'] == crop_code) & (df['chemical_code'] == chemical_code )]
    useYieldvsSoilTargetInstances = len(_.loc[_['UsesYieldVsSoilTestRange'] == True])
    yieldvsSoilTargetInstancesMatchesMaster = len(_.loc[_['yieldTargetsMatchesMasterCrop'] == True])
    _Arr = []
    _Arr.append(client_type)
    _Arr.append(crop_code)
    _Arr.append(crop_name)
    _Arr.append(chemical_code)
    _Arr.append(useYieldvsSoilTargetInstances)
    _Arr.append(yieldvsSoilTargetInstancesMatchesMaster)
    arr.append(_Arr)

In [28]:
arr = np.array(arr)

In [29]:
df_summary = pd.DataFrame(arr, columns = ["client_type","crop_code","crop_name","chemical_code","useYieldvsSoilTargetInstances","yieldvsSoilTargetInstancesMatchesMaster"])

,client_type,crop_code,crop_name,chemical_code,useYieldvsSoilTargetInstances,yieldvsSoilTargetInstancesMatchesMaster
15,Commercial,1292,Coffee (Olam),1,342,342
218,Commercial,1292,Coffee (Olam),1,342,342
421,Commercial,1292,Coffee (Olam),1,342,342
624,Commercial,1292,Coffee (Olam),1,342,342
827,Commercial,1292,Coffee (Olam),1,342,342
...,...,...,...,...,...,...
94491,AgViza,52,Passion Fruit,19,118,1
94636,AgViza,52,Passion Fruit,1,118,1
94683,AgViza,1292,Coffee (Olam),1,117,117
94694,AgViza,52,Passion Fruit,19,118,1
94839,AgViza,52,Passion Fruit,1,118,1

In [37]:
df_summary['yieldvsSoilTargetInstancesMatchesMaster'] = df_summary['yieldvsSoilTargetInstancesMatchesMaster'].astype("int")

In [39]:
df_summary.loc[df_summary['yieldvsSoilTargetInstancesMatchesMaster'] > 0]

,client_type,crop_code,crop_name,chemical_code,useYieldvsSoilTargetInstances,yieldvsSoilTargetInstancesMatchesMaster
15,Commercial,1292,Coffee (Olam),1,342,342
218,Commercial,1292,Coffee (Olam),1,342,342
421,Commercial,1292,Coffee (Olam),1,342,342
624,Commercial,1292,Coffee (Olam),1,342,342
827,Commercial,1292,Coffee (Olam),1,342,342
...,...,...,...,...,...,...
94491,AgViza,52,Passion Fruit,19,118,1
94636,AgViza,52,Passion Fruit,1,118,1
94683,AgViza,1292,Coffee (Olam),1,117,117
94694,AgViza,52,Passion Fruit,19,118,1
94839,AgViza,52,Passion Fruit,1,118,1

In [40]:
df_summary.to_csv("Summary_Nutrient_Req.csv")